### ISSUE TITLE
Can not install "Japan Country States"

### ISSUE THREAD

**Issue by cheart0** [OCA/l10n-japan#16]
module: l10n_jp_country_state
version: 12.0

**Steps to reproduce**
1. Tried to install all 3 modules, no error 
2. but "Japan Country States" module shows "Cancle installation" status instead of "Installed". Japanese country states still showing english instead of japanese.

**Current behavior**
Module not installed
![InstallJPNStates](https://user-images.githubusercontent.com/52992285/61352216-cd5deb80-a8a7-11e9-9f9d-5978d77b3146.jpg)

**Expected behavior**
Module can get installed and show "installed status" after done.

**Comment by TimLai125** [comment]
Hi @cheart0 
Have you installed `base_country_state_translatable` module which is the dependency of the `l10n_jp_country_state`?
FYI, you can find the `base_country_state_translatable` under this repo: https://github.com/OCA/partner-contact

**Comment by cheart0** [comment]
Hi TimLai125, 
Thx for your reply. I installed base_country_state_translatable because it was required by jp_country module. Today I uninstalled it and reinstalled base_country_state_translatable again and got error below even system reporting it is installed.
![image](https://user-images.githubusercontent.com/52992285/61608135-96634d80-ac8c-11e9-8fd5-837a804b68d2.png)

---------------------------
"The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.
Could not get content for /l10n_jp_address_layout/static/src/less/form_view.less defined in bundle 'web.assets_backend'."
---------------------------
Then I tried to install l10n_jp_country_state but got the same result as beginning.

Thanks
